name: run

on:
  schedule:
    - cron: '0 */5 * * *'
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: set up python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: install dependencies
        run: |
          pip install -r requirements.txt

      - name: run
        env:
          AI: ${{ secrets.AI }}
        run: |
          export CONDITION="IM_THE_REASON"
          touch "$CONDITION"
          while [[ -f "$CONDITION" ]]; do
            python3 main.py
            git pull
          done

